export const dev = window.location.origin.includes('localhost')
export const baseURL = dev ? 'http://localhost:3000' : ''
export const useSockets = false
export const domain = ''
export const clientId = ''
export const audience = ''
export const serviceId = 'service_3eltul8'
export const templateId = 'template_4x4jmzi'
export const userId = '6DHqwo97SmXhDEy-v'
export const myName = 'Anthony'
export const myEmail = 'wanderwithme1988@gmail.com'